// Package site builds isu's public website.
//
// M8 states the governing constraint plainly: **every sample shown on
// the site is generated by running this repo's binary during the build.** No
// hand-written terminal HTML, no invented output. So this package owns three
// things and nothing else — a scratch repository, a way to run isu against it,
// and a renderer that puts what isu printed into a page.
//
// # Why the samples are run in process
//
// A generator that shelled out to a built `isu` would be a second place in
// internal/ that constructs a command, and M2-S1's rule is that internal/gitx
// is the only one. It would also be a generator that could be pointed at a
// stale binary. `cli.Run` takes its streams, its directory, its clock and its
// environment as arguments — M4-S1 built it that way so the tests would be end
// to end through the product — and the site build wants exactly the same thing
// for exactly the same reason. The binary in this repository and the code this
// package calls are the same code.
//
// # Why the fixture is written with plumbing
//
// The samples are golden files: `make site` writes them and `go test` fails
// when the committed page and the regenerated one differ. That only works if
// the fixture is a byte-for-byte function of this file, so every commit is
// dated from a fixed clock, every author is named here, and no value is taken
// from the machine the build runs on. gittest builds repositories the same way
// but takes a testing.TB, and a site build is not a test.
package site

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"time"

	"github.com/dgorshkov/isu/internal/gitx"
	"github.com/dgorshkov/isu/internal/issue"
)

// Now is the moment every sample on the site is rendered as of.
//
// It is a constant rather than the wall clock because "3d ago" is a difference
// between two times, and a page whose ages drift every day is a page whose
// diff is noise. Commit dates below are offsets from it.
var Now = time.Date(2026, 4, 14, 10, 15, 0, 0, time.UTC)

// Trunk is the fixture's default branch, named here rather than inherited from
// the builder's init.defaultBranch.
const Trunk = "main"

// prefix is the fixture repository's issue id prefix.
const prefix = "APP"

// author is who writes a fixture commit when a step does not say.
const author = "Dana Okafor <dana@example.invalid>"

// scratch is the repository the samples run against.
//
// Every method folds its error into err and does nothing once one is set, so
// that scripting a fixture reads as a list of steps rather than a ladder of
// error checks. It is the shape gittest uses for the same reason; the
// difference is that this one is used outside a test, so it returns the
// failure instead of ending the process.
type scratch struct {
	dir  string
	git  *gitx.Git
	ctx  context.Context //nolint:containedctx // a builder's steps share one
	err  error
	when time.Time
	who  string
	// head is the branch the next commit extends and the ref it moves.
	head string
	// tips remembers each branch's tip, so a branch can be started from trunk
	// without asking git where trunk is.
	tips map[string]string
	// trees remembers each branch's tree, which is what the next commit on it
	// is built over.
	trees map[string]string
	// files is the fixture's content, per branch, so that a commit can be
	// expressed as the files it changes rather than as a whole tree.
	files map[string]map[string]string
}

// newScratch initialises an empty repository in dir.
func newScratch(ctx context.Context, dir string) *scratch {
	s := &scratch{
		ctx:   ctx,
		dir:   dir,
		when:  Now,
		who:   author,
		head:  Trunk,
		tips:  map[string]string{},
		trees: map[string]string{},
		files: map[string]map[string]string{Trunk: {}},
	}

	s.git, s.err = gitx.New(dir, gitx.WithEnv(s.env))
	s.do(func() error { return s.git.Run(ctx, "init", "--quiet", "-b", Trunk, ".") })

	return s
}

// env is the whole of what the fixture's git reads from its surroundings.
//
// Identity and dates are set here rather than in a config file so that a
// repository can be built with no write to .git at all, and the configuration
// git has no environment variable for goes in through GIT_CONFIG_COUNT, which
// is the documented way to say "this run, and not the user's file".
func (s *scratch) env(base []string) []string {
	stamp := s.when.Format(time.RFC3339)
	name, mail, _ := strings.Cut(strings.TrimSuffix(s.who, ">"), " <")

	settings := []string{
		"commit.gpgsign=false",
		"tag.gpgsign=false",
		"core.autocrlf=false",
		"gc.auto=0",
		"advice.detachedHead=false",
		"init.defaultBranch=" + Trunk,
	}

	env := append(base,
		"GIT_AUTHOR_NAME="+name, "GIT_AUTHOR_EMAIL="+mail, "GIT_AUTHOR_DATE="+stamp,
		"GIT_COMMITTER_NAME="+name, "GIT_COMMITTER_EMAIL="+mail, "GIT_COMMITTER_DATE="+stamp,
		fmt.Sprintf("GIT_CONFIG_COUNT=%d", len(settings)),
	)

	for i, setting := range settings {
		key, value, _ := strings.Cut(setting, "=")
		env = append(env,
			fmt.Sprintf("GIT_CONFIG_KEY_%d=%s", i, key),
			fmt.Sprintf("GIT_CONFIG_VALUE_%d=%s", i, value))
	}

	return env
}

// do runs one step unless an earlier one already failed.
func (s *scratch) do(step func() error) {
	if s.err != nil {
		return
	}

	s.err = step()
}

// at moves the clock every later commit is stamped with.
func (s *scratch) at(ago time.Duration) *scratch {
	s.when = Now.Add(-ago)

	return s
}

// as names who writes every later commit.
func (s *scratch) as(who string) *scratch {
	s.who = who

	return s
}

// file stages one file on the current branch.
func (s *scratch) file(path, body string) *scratch {
	if s.err == nil {
		s.files[s.head][path] = body
	}

	return s
}

// issueFile stages an issue, encoded by the package that owns the format.
func (s *scratch) issueFile(i *issue.Issue) *scratch {
	i.Schema = issue.CurrentSchema
	i.Folder = i.ID

	return s.file("issues/"+i.ID+"/README.md", string(i.Encode()))
}

// commit writes everything staged on the current branch as one commit.
func (s *scratch) commit(subject string) *scratch {
	s.do(func() error {
		edits := make([]gitx.TreeEdit, 0, len(s.files[s.head]))
		for _, path := range sorted(s.files[s.head]) {
			edits = append(edits, gitx.TreeEdit{Path: path, Blob: []byte(s.files[s.head][path])})
		}

		tree, err := s.git.BuildTree(s.ctx, "", edits)
		if err != nil {
			return err
		}

		var parents []string
		if tip := s.tips[s.head]; tip != "" {
			parents = append(parents, tip)
		}

		commit, err := s.git.CommitTree(s.ctx, tree, parents, subject+"\n")
		if err != nil {
			return err
		}

		s.tips[s.head] = commit
		s.trees[s.head] = tree

		return s.git.UpdateRef(s.ctx, "refs/heads/"+s.head, commit, "")
	})

	return s
}

// branch starts a branch from the current one and switches to it.
func (s *scratch) branch(name string) *scratch {
	if s.err == nil {
		from := s.head
		s.tips[name] = s.tips[from]
		s.trees[name] = s.trees[from]
		s.files[name] = clone(s.files[from])
		s.head = name
	}

	return s
}

// checkout points HEAD at a branch that already exists.
func (s *scratch) checkout(name string) *scratch {
	if s.err == nil {
		s.head = name
	}

	return s
}

// publish gives the repository an origin and pushes every branch to it, so
// that the samples say what a working clone says rather than "no remote refs".
func (s *scratch) publish() *scratch {
	remote := s.dir + ".origin"

	s.do(func() error { return s.git.Run(s.ctx, "init", "--quiet", "--bare", remote) })
	s.do(func() error { return s.git.Run(s.ctx, "remote", "add", "origin", remote) })
	s.do(func() error { return s.git.Push(s.ctx, "origin", "refs/heads/*:refs/heads/*") })
	s.do(func() error {
		return s.git.Run(s.ctx,
			"symbolic-ref", "refs/remotes/origin/HEAD", "refs/remotes/origin/"+Trunk)
	})

	return s
}

// settle points HEAD at branch and checks it out, so the fixture on disk is
// what a person who cloned it would see.
func (s *scratch) settle(branch string) *scratch {
	s.do(func() error {
		return s.git.Run(s.ctx, "symbolic-ref", "HEAD", "refs/heads/"+branch)
	})
	s.do(func() error { return s.git.Run(s.ctx, "reset", "--hard", "--quiet") })

	return s
}

// sorted is a map's keys in order, which is what makes a tree a function of the
// fixture rather than of Go's map iteration.
func sorted(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}

	slices.Sort(keys)

	return keys
}

func clone(m map[string]string) map[string]string {
	out := make(map[string]string, len(m))
	for k, v := range m {
		out[k] = v
	}

	return out
}

// Fixture builds the repository every sample on the site is taken from, and
// returns its path.
//
// It is a small team's repository three months in: an epic, the bug everybody
// has an opinion about, a story somebody claimed this morning, a chore that
// landed, a spike that was answered, one thing that was dropped with a reason,
// and one report that arrived on a branch and has not been triaged. Every
// derived status in the data model is on the board, because a landing page that
// shows only the easy half is a landing page that is lying by omission.
func Fixture(ctx context.Context, dir string) (string, error) {
	repo := filepath.Join(dir, "acme-app")
	if err := os.MkdirAll(repo, 0o750); err != nil {
		return "", err
	}

	s := newScratch(ctx, repo)

	build(s)

	if s.err != nil {
		return "", fmt.Errorf("building the sample repository: %w", s.err)
	}

	return repo, nil
}

// Writable builds a repository the documentation may change: one commit, no
// .isu.yml, an origin to push to, and the identity git needs to write a commit.
//
// docs/getting-started.md runs against this one, because a page that says
// `isu init` and then never runs it is the page most likely to be wrong and
// the one nobody can afford to be wrong. The identity is set with `git config`
// rather than through the environment: isu runs its own git, and what it reads
// is the repository's configuration and not this process's.
func Writable(ctx context.Context, dir string) (string, error) {
	repo := filepath.Join(dir, "new-project")
	if err := os.MkdirAll(repo, 0o750); err != nil {
		return "", err
	}

	s := newScratch(ctx, repo)

	for _, setting := range [][2]string{
		{"user.name", "Dana Okafor"},
		{"user.email", "dana@example.invalid"},
		{"commit.gpgsign", "false"},
		{"tag.gpgsign", "false"},
	} {
		s.do(func() error { return s.git.Run(ctx, "config", setting[0], setting[1]) })
	}

	s.file("README.md", "# new-project\n").
		file("src/main.go", "package main\n\nfunc main() {}\n").
		commit("first commit").
		publish().
		settle(Trunk)

	if s.err != nil {
		return "", fmt.Errorf("building a repository for the documentation: %w", s.err)
	}

	return repo, nil
}

// The fixture's ids. They are written out rather than generated: an id is
// thirty bits of hash over eight random bytes (the data model), and a page whose
// ids change on every build is a page with no diff worth reading.
const (
	idEpic    = prefix + "-40b1cc"
	idLogin   = prefix + "-7f3akq"
	idQueue   = prefix + "-9cx2rt"
	idLint    = prefix + "-2mdz8k"
	idSpike   = prefix + "-x4h7vb"
	idDropped = prefix + "-8ptr5s"
	idReport  = prefix + "-63kqwn"
	idReceipt = prefix + "-b5n3kt"
	idStatus  = prefix + "-5wq7dn"
)

// ClaimBranch is the branch the story sample is claimed on.
const ClaimBranch = "isu/" + idQueue

// ReceiptBranch is the branch that claimed and then resolved the receipt story.
// It is still here after the merge, which is what a branch usually is.
const ReceiptBranch = "isu/" + idReceipt

// ReportBranch carries an issue that is not on trunk yet.
const ReportBranch = "report/firefox-500"

const day = 24 * time.Hour

func build(s *scratch) {
	s.at(90*day).
		file(".isu.yml", "prefix: "+prefix+"\nagents:\n  - releasebot\n").
		file("README.md", "# acme-app\n\nThe sign-up and billing service.\n").
		file("src/signup.ts", "export const signup = () => {};\n").
		commit("set up the repository")

	s.at(52 * day).
		issueFile(&issue.Issue{
			ID: idEpic, Title: "Make sign-up reliable", Type: issue.TypeEpic,
			Owner: "dana", Created: day90(52),
			Body: "Everything between the landing page and the first invoice.\n",
		}).
		issueFile(&issue.Issue{
			ID: idLogin, Title: "Login retries drop the second attempt",
			Type: issue.TypeBug, State: issue.StateOpen, Owner: "dana",
			Created: day90(52), Priority: issue.PriorityP1, Parent: idEpic,
			Repro: "sign in, fail once, retry within 5s",
			Body: "The retry reuses the first request's nonce, so the second POST " +
				"is rejected before it reaches the handler.\n",
		}).
		issueFile(&issue.Issue{
			ID: idQueue, Title: "Show the sign-up queue on the board",
			Type: issue.TypeStory, State: issue.StateOpen, Owner: "priya",
			Created: day90(52), Parent: idEpic,
			Acceptance: "the board shows queue depth and the oldest waiting account",
		}).
		issueFile(&issue.Issue{
			ID: idLint, Title: "Upgrade the linter", Type: issue.TypeChore,
			State: issue.StateOpen, Owner: "sam", Created: day90(52),
			Priority: issue.PriorityP3,
		}).
		issueFile(&issue.Issue{
			ID: idSpike, Title: "What does a failed payment cost us?",
			Type: issue.TypeSpike, State: issue.StateOpen, Owner: "dana",
			Created: day90(52), Parent: idEpic,
			Question: "how much revenue does a declined card lose before the retry?",
		}).
		issueFile(&issue.Issue{
			ID: idDropped, Title: "Rewrite the CSS in another framework",
			Type: issue.TypeChore, State: issue.StateOpen, Owner: "sam",
			Created: day90(52),
		}).
		issueFile(receiptIssue(issue.StateOpen)).
		issueFile(&issue.Issue{
			ID: idStatus, Title: "Publish a status page", Type: issue.TypeChore,
			State: issue.StateOpen, Owner: "sam", Created: day90(40),
			Priority: issue.PriorityP3, BlockedBy: []string{idLogin},
		}).
		commit("report the first eight issues")

	// A chore that landed, and something dropped with a reason beside it.
	s.at(21*day).as("Sam Ellis <sam@example.invalid>").
		file("package.json", "{\n  \"devDependencies\": { \"eslint\": \"9.0.0\" }\n}\n").
		issueFile(&issue.Issue{
			ID: idLint, Title: "Upgrade the linter", Type: issue.TypeChore,
			State: issue.StateResolved, Owner: "sam", Created: day90(52),
			Priority: issue.PriorityP3,
		}).
		issueFile(&issue.Issue{
			ID: idDropped, Title: "Rewrite the CSS in another framework",
			Type: issue.TypeChore, State: issue.StateDropped, Owner: "sam",
			Created: day90(52), Reason: "the framework we would move to is younger than this bug",
			Resolution: issue.ResolutionWontfix,
		}).
		commit("upgrade the linter\n\nIsu-Resolves: " + idLint)

	// A spike is answered by a file beside it, not by a change to the product.
	s.at(9*day).
		file("issues/"+idSpike+"/findings.md",
			"# What a declined card costs\n\n£4.10 per account, mostly in support time.\n").
		issueFile(&issue.Issue{
			ID: idSpike, Title: "What does a failed payment cost us?",
			Type: issue.TypeSpike, State: issue.StateResolved, Owner: "dana",
			Created: day90(52), Parent: idEpic,
			Question: "how much revenue does a declined card lose before the retry?",
		}).
		commit("answer " + idSpike + "\n\nIsu-Resolves: " + idSpike)

	s.at(3*time.Hour).
		file("src/retry.ts", "export const retry = () => {};\n").
		commit("start on the retry path")

	// The claim: a branch that flips the state and has done nothing else yet,
	// which is what `isu claim` writes and what the evidence check refuses.
	s.at(6 * time.Hour).as("Priya Raman <priya@example.invalid>").
		branch(ClaimBranch).
		issueFile(&issue.Issue{
			ID: idQueue, Title: "Show the sign-up queue on the board",
			Type: issue.TypeStory, State: issue.StateResolved, Owner: "priya",
			Created: day90(52), Parent: idEpic,
			Acceptance: "the board shows queue depth and the oldest waiting account",
		}).
		commit("claim " + idQueue + "\n\nIsu-Claim: 4f2a1de9c07b3856")

	// A report that arrived on a branch and has not reached trunk: the data model
	// calls that awaiting triage, and it is the status a tracker with a
	// database cannot express at all.
	s.at(26 * time.Hour).as("Sam Ellis <sam@example.invalid>").
		checkout(Trunk).branch(ReportBranch).
		issueFile(&issue.Issue{
			ID: idReport, Title: "Sign-up page 500s on Firefox", Type: issue.TypeBug,
			State: issue.StateOpen, Owner: "sam", Created: day90(1),
			Priority: issue.PriorityP0, Parent: idEpic,
			Repro: "open /signup in Firefox 138 with cookies blocked",
		}).
		commit("report " + idReport)

	// A claim that was worked and then landed on trunk. This is the loop the
	// whole product describes, and the fixture did not contain one: every issue
	// on the board was either finished before the samples start or still in
	// flight, so the site could show four states and no transition between two
	// of them.
	//
	// The branch is left where it is, because a branch outlives the squash that
	// merged it, and trunk is what decides. So the same issue, with nothing
	// edited and no flag on the second command, reads `in progress` at the
	// commit before the merge and `done` at the one after it.
	s.at(30 * time.Hour).as("Priya Raman <priya@example.invalid>").
		checkout(Trunk).branch(ReceiptBranch).
		issueFile(receiptIssue(issue.StateResolved)).
		commit("claim " + idReceipt + "\n\nIsu-Claim: 91c4be07a2d5f318")

	s.at(time.Hour).as("Priya Raman <priya@example.invalid>").
		checkout(Trunk).
		file("src/receipt.ts", "export const receipt = () => {};\n").
		issueFile(receiptIssue(issue.StateResolved)).
		commit("send one receipt per paid invoice\n\nIsu-Resolves: " + idReceipt)

	s.publish().settle(ClaimBranch)
}

// receiptIssue is the story that gets claimed, worked and merged. It is written
// once and stamped twice — onto the branch and onto trunk — because the only
// thing that may differ between those two copies is the state, and a second
// literal is a second place for the rest of it to drift.
func receiptIssue(state issue.State) *issue.Issue {
	return &issue.Issue{
		ID: idReceipt, Title: "Send a receipt after the first invoice",
		Type: issue.TypeStory, State: state, Owner: "priya",
		Created: day90(40), Parent: idEpic,
		Acceptance: "a paid invoice sends one receipt, and only one",
	}
}

// day90 is a created date, as many days before Now as the caller says.
func day90(days int) time.Time {
	return Now.AddDate(0, 0, -days).Truncate(day)
}
